/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

module.exports = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // defaultSidebar: [{ type: "autogenerated", dirName: "." }],

  mySidebar: [
    {
      type: "doc",
      label: "Introduction",
      id: "intro",
    },
    {
      type: "category",
      label: "Getting Started",
      collapsed: false,
      items: [
        {
          type: "doc",
          id: "guides/configuration",
          label: "Configuration Project",
        },
        {
          type: "category",
          label: "Frameworks",
          items: [
            {
              type: "ref",
              label: "creat-react-app",
              id: "guides/creat-react-app",
            },
            {
              type: "ref",
              label: "nextjs",
              id: "guides/nextjs",
            },
            {
              type: "ref",
              label: "gatsby",
              id: "guides/gatsby",
            },
          ],
        },
        {
          type: "doc",
          id: "guides/import",
          label: "Import Project",
        },
      ],
    },
    {
      type: "category",
      label: "reference",
      items: [
        {
          type: "category",
          label: "Layout",
          items: [
            "reference/layout/display",
            "reference/layout/position",
            "reference/layout/flex",
            "reference/layout/grid",
            "reference/layout/float",
            "reference/layout/visibility",
            "reference/layout/boxSizing",
            "reference/layout/overflow",
            "reference/layout/overscroll",
            "reference/layout/zIndex",
            "reference/layout/container",
            "reference/layout/objectFit",
            "reference/layout/objectPosition",
          ],
        },
        {
          type: "doc",
          id: "guides/import",
          label: "Import Project",
        },
      ],
    },
    {
      type: "category",
      label: "Tutorial",
      items: ["tutorial/congratulations"],
    },
  ],
};
