/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

module.exports = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // defaultSidebar: [{ type: "autogenerated", dirName: "." }],

  mySidebar: [
    {
      type: "doc",
      label: "Introduction",
      id: "intro",
    },
    {
      type: "category",
      label: "Getting Started",
      collapsed: false,
      items: [
        "guides/configuration",
        "guides/import",
        {
          type: "ref",
          id: "guides/creat-react-app",
        },
        {
          type: "ref",
          id: "guides/nextjs",
        },
      ],
    },
    {
      type: "category",
      label: "Tutorial",
      items: ["tutorial/congratulations"],
    },
  ],
};
